package main

func gameClock(min, sec int) float32 {
	return float32(min*60 + sec)
}

const bm = "badguys_melee"
const br = "badguys_ranged"
const bs = "badguys_siege"
const bf = "badguys_flagbearer"
const gm = "goodguys_melee"
const gr = "goodguys_ranged"
const gs = "goodguys_siege"
const gf = "goodguys_flagbearer"

var (
	replay8915936762 = &Replay{ID: "8915936762", SkillLevel: SkillDivine}
	replay8934466456 = &Replay{ID: "8934466456", SkillLevel: SkillDivine}
	replay8937936492 = &Replay{ID: "8937936492", SkillLevel: SkillLegend}
	replay8941733752 = &Replay{ID: "8941733752", SkillLevel: SkillPro}
	replay8941817475 = &Replay{ID: "8941817475", SkillLevel: SkillPro}
	replay8941961575 = &Replay{ID: "8941961575", SkillLevel: SkillCrusader}
	replay8943058440 = &Replay{ID: "8943058440", SkillLevel: SkillGuardian}
	replay8951306658 = &Replay{ID: "8951306658", SkillLevel: SkillArchon}
)

var (
	rhWarlock         = &ReplayHero{Replay: replay8915936762, Hero: "Warlock", Role: RoleSupport}
	rhPhantomAssassin = &ReplayHero{Replay: replay8934466456, Hero: "Phantom Assassin", Role: RoleCore}
	rhAntimage        = &ReplayHero{Replay: replay8937936492, Hero: "Antimage", Role: RoleCore}
	rhUrsa            = &ReplayHero{Replay: replay8937936492, Hero: "Ursa", Role: RoleCore}
	rhOD              = &ReplayHero{Replay: replay8937936492, Hero: "Obsidian Destroyer", Role: RoleCore}
	rhSven            = &ReplayHero{Replay: replay8941733752, Hero: "Sven", Role: RoleCore}
	rhSlark           = &ReplayHero{Replay: replay8941817475, Hero: "Slark", Role: RoleCore}
	rhJuggernaut      = &ReplayHero{Replay: replay8941961575, Hero: "Juggernaut", Role: RoleCore}
	rhTerrorblade     = &ReplayHero{Replay: replay8941961575, Hero: "Terrorblade", Role: RoleCore}
	rhShadowFiend     = &ReplayHero{Replay: replay8941961575, Hero: "Shadow Fiend", Role: RoleCore}
	rhZuus            = &ReplayHero{Replay: replay8943058440, Hero: "Zuus", Role: RoleCore}
	rhJakiro          = &ReplayHero{Replay: replay8951306658, Hero: "Jakiro", Role: RoleSupport}
	rhSkywrathMage    = &ReplayHero{Replay: replay8951306658, Hero: "Skywrath Mage", Role: RoleSupport}
)

// qualityCases — edit freely; not part of the build gate.

var qualityCases = []qualityCase{
	// Replay 8915936762
	// =============================================
	{
		Label:         "2:46 missed deny on flagbearer",
		Description:   "Warlock right-clicks ally flagbearer low; Huskar kills it",
		ReplayHero:    rhWarlock,
		From:          gameClock(2, 44),
		To:            gameClock(2, 47),
		CreepContains: "badguys_flagbearer",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagDeny},
	},
	{
		Label:         "2:52 creep dies to Fatal Bonds",
		Description:   "Allied melee creep death from Fatal Bonds spread damage",
		ReplayHero:    rhWarlock,
		From:          gameClock(2, 51),
		To:            gameClock(2, 53),
		CreepContains: "goodguys_melee",
		ExpectMiss:    false,
		Tags:          []CaseTag{TagSpell, TagAOE},
	},
	{
		Label:         "2:55 creep dies to Fatal Bonds",
		Description:   "Allied melee creep death from Fatal Bonds spread damage",
		ReplayHero:    rhWarlock,
		From:          gameClock(2, 54),
		To:            gameClock(2, 56),
		CreepContains: "goodguys_melee",
		ExpectMiss:    false,
		Tags:          []CaseTag{TagSpell, TagAOE},
	},
	{
		Label:         "2:58 creep dies to Fatal Bonds",
		Description:   "Allied ranged creep death from Fatal Bonds spread damage",
		ReplayHero:    rhWarlock,
		From:          gameClock(2, 57),
		To:            gameClock(2, 59),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    false,
		Tags:          []CaseTag{TagSpell, TagAOE},
	},
	// Replay 8934466456
	// =============================================
	{
		Label:         "1:08-1:10 missed last hit on melee creep",
		Description:   "Phantom Assassin missed last hit on melee creep with a dagger",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(1, 8),
		To:            gameClock(1, 10),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooEarly},
	},
	{
		Label:         "1:17-1:19 AFK",
		Description:   "AFK",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(1, 17),
		To:            gameClock(1, 19),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "dagger",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(1, 39),
		To:            gameClock(1, 41),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "no attack or too late",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(1, 54),
		To:            gameClock(1, 56),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagTooLate},
	},
	{
		Label:         "we attacked a creep on the same tick as 2 allied creeps, didnt count as last hit",
		Description:   "1st creep attack didnt show on a log, only the killing blow did from 2nd creep",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(2, 10),
		To:            gameClock(2, 11),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(2, 11),
		To:            gameClock(2, 12),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(2, 32),
		To:            gameClock(2, 34),
		CreepContains: "goodguys_flagbearer",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(2, 40),
		To:            gameClock(2, 42),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(3, 4),
		To:            gameClock(3, 5),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(3, 48),
		To:            gameClock(3, 50),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhPhantomAssassin,
		From:          gameClock(4, 0),
		To:            gameClock(4, 2),
		CreepContains: "badguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	// Replay 8937936492, Antimage
	// =============================================
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhAntimage,
		From:          gameClock(1, 38),
		To:            gameClock(1, 40),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhAntimage,
		From:          gameClock(1, 45),
		To:            gameClock(1, 47),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhAntimage,
		From:          gameClock(3, 51),
		To:            gameClock(3, 53),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhAntimage,
		From:          gameClock(3, 56),
		To:            gameClock(3, 57),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhAntimage,
		From:          gameClock(3, 59),
		To:            gameClock(4, 1),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagTooLate, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhAntimage,
		From:          gameClock(4, 11),
		To:            gameClock(4, 13),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagTooEarly, TagAutoAttack},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhAntimage,
		From:          gameClock(4, 39),
		To:            gameClock(4, 41),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhAntimage,
		From:          gameClock(5, 5),
		To:            gameClock(5, 8),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhAntimage,
		From:          gameClock(5, 48),
		To:            gameClock(5, 50),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhAntimage,
		From:          gameClock(6, 2),
		To:            gameClock(6, 4),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	// Replay 8937936492, Ursa
	// =============================================
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhUrsa,
		From:          gameClock(0, 47),
		To:            gameClock(0, 49),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhUrsa,
		From:          gameClock(1, 9),
		To:            gameClock(1, 11),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhUrsa,
		From:          gameClock(2, 39),
		To:            gameClock(2, 41),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhUrsa,
		From:          gameClock(2, 46),
		To:            gameClock(2, 48),
		CreepContains: "badguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhUrsa,
		From:          gameClock(3, 9),
		To:            gameClock(3, 11),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhUrsa,
		From:          gameClock(3, 54),
		To:            gameClock(3, 57),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhUrsa,
		From:          gameClock(5, 56),
		To:            gameClock(5, 59),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "hidden in astral by shadow demon",
		ReplayHero:    rhUrsa,
		From:          gameClock(6, 37),
		To:            gameClock(6, 39),
		CreepContains: bm,
		ExpectMiss:    false,
		Tags:          []CaseTag{},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhUrsa,
		From:          gameClock(7, 41),
		To:            gameClock(7, 43),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagFreeFarming},
	},
	// Replay 8937936492, Outworld Destroyer
	// =============================================
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(0, 46),
		To:            gameClock(0, 49),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(0, 49),
		To:            gameClock(0, 51),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(1, 48),
		To:            gameClock(1, 50),
		CreepContains: "badguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(1, 50),
		To:            gameClock(1, 52),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(1, 59),
		To:            gameClock(2, 2),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(2, 37),
		To:            gameClock(2, 39),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagTooLate, TagAutoAttack, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(4, 12),
		To:            gameClock(4, 14),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(4, 54),
		To:            gameClock(4, 56),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagFreeFarming, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(4, 58),
		To:            gameClock(5, 0),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(5, 2),
		To:            gameClock(5, 4),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(5, 23),
		To:            gameClock(5, 25),
		CreepContains: "badguys_flagbearer",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(5, 35),
		To:            gameClock(5, 37),
		CreepContains: "badguys_siege",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(6, 14),
		To:            gameClock(6, 15),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(6, 17),
		To:            gameClock(6, 19),
		CreepContains: "badguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(7, 16),
		To:            gameClock(7, 19),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate, TagTower, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(7, 52),
		To:            gameClock(7, 54),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(7, 52),
		To:            gameClock(7, 54),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(7, 58),
		To:            gameClock(8, 0),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(9, 7),
		To:            gameClock(9, 9),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(9, 34),
		To:            gameClock(9, 36),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(10, 29),
		To:            gameClock(10, 31),
		CreepContains: "badguys_flagbearer",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(13, 11),
		To:            gameClock(13, 13),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(13, 54),
		To:            gameClock(13, 56),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(14, 24),
		To:            gameClock(14, 26),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(14, 24),
		To:            gameClock(14, 26),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhOD,
		From:          gameClock(14, 54),
		To:            gameClock(14, 57),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	// Replay 8941961575 Juggernaut
	// =================================================================
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(2, 2),
		To:            gameClock(2, 4),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(2, 36),
		To:            gameClock(2, 38),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(2, 45),
		To:            gameClock(2, 48),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(3, 45),
		To:            gameClock(3, 48),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(4, 37),
		To:            gameClock(4, 40),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(5, 41),
		To:            gameClock(5, 43),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(5, 56),
		To:            gameClock(5, 58),
		CreepContains: "badguys_siege",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(6, 38),
		To:            gameClock(6, 40),
		CreepContains: "badguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "blade fury through creeps",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(8, 35),
		To:            gameClock(8, 45),
		CreepContains: bm,
		ExpectMiss:    false,
		Tags:          []CaseTag{},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(9, 20),
		To:            gameClock(9, 23),
		CreepContains: "badguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "stunned",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(11, 38),
		To:            gameClock(11, 41),
		CreepContains: bm,
		ExpectMiss:    false,
		Tags:          []CaseTag{},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(15, 19),
		To:            gameClock(15, 23),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(15, 39),
		To:            gameClock(15, 43),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(15, 42),
		To:            gameClock(15, 45),
		CreepContains: "badguys_flagbearer",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(19, 14),
		To:            gameClock(19, 16),
		CreepContains: "badguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(21, 44),
		To:            gameClock(21, 47),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhJuggernaut,
		From:          gameClock(22, 9),
		To:            gameClock(22, 12),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming, TagAOE},
	},
	// Replay 8941961575 Terrorblade
	// =================================================================
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(1, 39),
		To:            gameClock(1, 41),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(1, 50),
		To:            gameClock(1, 52),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(2, 0),
		To:            gameClock(2, 3),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(2, 27),
		To:            gameClock(2, 29),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(2, 47),
		To:            gameClock(2, 51),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(3, 33),
		To:            gameClock(3, 37),
		CreepContains: "badguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(3, 43),
		To:            gameClock(3, 46),
		CreepContains: "badguys_flagbearer",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(4, 20),
		To:            gameClock(4, 24),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(4, 32),
		To:            gameClock(4, 35),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(4, 59),
		To:            gameClock(5, 1),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(5, 11),
		To:            gameClock(5, 13),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(5, 13),
		To:            gameClock(5, 14),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(5, 15),
		To:            gameClock(5, 18),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(5, 52),
		To:            gameClock(5, 55),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(5, 58),
		To:            gameClock(6, 1),
		CreepContains: "goodguys_siege",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(6, 1),
		To:            gameClock(6, 4),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(6, 11),
		To:            gameClock(6, 14),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(8, 23),
		To:            gameClock(8, 27),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(9, 42),
		To:            gameClock(9, 44),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(10, 13),
		To:            gameClock(10, 15),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagIllusion},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(10, 30),
		To:            gameClock(10, 31),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(14, 24),
		To:            gameClock(14, 26),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(14, 57),
		To:            gameClock(14, 59),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagGlyph, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(16, 33),
		To:            gameClock(16, 35),
		CreepContains: "goodguys_flagbearer",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(16, 34),
		To:            gameClock(16, 36),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(16, 39),
		To:            gameClock(16, 41),
		CreepContains: "goodguys_siege",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(17, 37),
		To:            gameClock(17, 41),
		CreepContains: "goodguys_flagbearer",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(17, 41),
		To:            gameClock(17, 45),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(17, 41),
		To:            gameClock(17, 45),
		CreepContains: "goodguys_ranged",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhTerrorblade,
		From:          gameClock(23, 57),
		To:            gameClock(23, 59),
		CreepContains: "goodguys_melee",
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	// Replay 8941961575 Shadow Fiend
	// =================================================================
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(0, 27),
		To:            gameClock(0, 31),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(0, 41),
		To:            gameClock(0, 44),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(1, 13),
		To:            gameClock(1, 15),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "failed to deny vs higher melee damage",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(1, 31),
		To:            gameClock(1, 38),
		CreepContains: "goodguys_melee",
		ExpectMiss:    false,
		Tags:          []CaseTag{TagDeny},
	},
	{
		Label:         "failed to deny vs higher melee damage",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(1, 41),
		To:            gameClock(1, 45),
		CreepContains: "goodguys_melee",
		ExpectMiss:    false,
		Tags:          []CaseTag{TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(1, 43),
		To:            gameClock(1, 45),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(1, 45),
		To:            gameClock(1, 46),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(1, 46),
		To:            gameClock(1, 48),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate, TagTower},
	},
	{
		Label:         "potentially impossible lh",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(1, 46),
		To:            gameClock(1, 49),
		CreepContains: br,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "potentially impossible lh",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(1, 57),
		To:            gameClock(2, 0),
		CreepContains: gm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "failed to deny vs higher melee damage",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(2, 1),
		To:            gameClock(2, 3),
		CreepContains: gm,
		ExpectMiss:    false,
		Tags:          []CaseTag{TagDeny},
	},
	{
		Label:         "potentially impossible lh",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(1, 57),
		To:            gameClock(2, 0),
		CreepContains: gm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "h",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(2, 6),
		To:            gameClock(2, 9),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(2, 9),
		To:            gameClock(2, 11),
		CreepContains: br,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(2, 39),
		To:            gameClock(2, 41),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(2, 53),
		To:            gameClock(2, 56),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(5, 15),
		To:            gameClock(5, 17),
		CreepContains: br,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(5, 24),
		To:            gameClock(5, 28),
		CreepContains: bf,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(5, 53),
		To:            gameClock(5, 54),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(5, 53),
		To:            gameClock(5, 54),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(5, 56),
		To:            gameClock(5, 49),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(6, 22),
		To:            gameClock(6, 25),
		CreepContains: bf,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(6, 37),
		To:            gameClock(6, 39),
		CreepContains: gr,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(6, 51),
		To:            gameClock(6, 53),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(7, 46),
		To:            gameClock(7, 49),
		CreepContains: bf,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(13, 21),
		To:            gameClock(13, 24),
		CreepContains: bf,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAOE, TagSpell},
	},
	{
		Label:         "Middle of the fight",
		Description:   "",
		ReplayHero:    rhShadowFiend,
		From:          gameClock(18, 50),
		To:            gameClock(19, 30),
		CreepContains: bm,
		ExpectMiss:    false,
		Tags:          []CaseTag{},
	},
	// Replay 8943058440 Zuus
	// =====================================================================
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(0, 21),
		To:            gameClock(0, 24),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAOE, TagAutoAttack, TagTooLate},
	},
	{
		Label:         "killed by weaver but we have damage advantage",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(1, 0),
		To:            gameClock(1, 3),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "killed by weaver but we have damage advantage",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(1, 3),
		To:            gameClock(1, 6),
		CreepContains: gm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(1, 12),
		To:            gameClock(1, 13),
		CreepContains: gr,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagTooLate, TagDeny},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(1, 36),
		To:            gameClock(1, 39),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAOE, TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(1, 54),
		To:            gameClock(1, 58),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(2, 12),
		To:            gameClock(2, 15),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(2, 15),
		To:            gameClock(2, 17),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(2, 31),
		To:            gameClock(2, 34),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(2, 56),
		To:            gameClock(2, 59),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(3, 16),
		To:            gameClock(3, 19),
		CreepContains: br,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(3, 27),
		To:            gameClock(3, 30),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(4, 2),
		To:            gameClock(4, 5),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(4, 26),
		To:            gameClock(4, 30),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate, TagSpell},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(5, 13),
		To:            gameClock(5, 14),
		CreepContains: br,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagAOE, TagTower, TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(5, 14),
		To:            gameClock(5, 16),
		CreepContains: br,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate, TagTower},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(5, 32),
		To:            gameClock(5, 34),
		CreepContains: bf,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(5, 47),
		To:            gameClock(5, 50),
		CreepContains: bs,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(6, 25),
		To:            gameClock(6, 26),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(6, 32),
		To:            gameClock(6, 35),
		CreepContains: bf,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(6, 37),
		To:            gameClock(6, 39),
		CreepContains: br,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested, TagFreeFarming},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(13, 7),
		To:            gameClock(13, 9),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(15, 58),
		To:            gameClock(16, 0),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(15, 58),
		To:            gameClock(16, 0),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(16, 0),
		To:            gameClock(16, 2),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagAOE, TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(20, 58),
		To:            gameClock(21, 0),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagAOE, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(21, 0),
		To:            gameClock(21, 2),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagAOE, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(21, 11),
		To:            gameClock(21, 17),
		CreepContains: bf,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagAOE},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(21, 51),
		To:            gameClock(21, 53),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(24, 24),
		To:            gameClock(24, 27),
		CreepContains: bf,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhZuus,
		From:          gameClock(24, 59),
		To:            gameClock(25, 2),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagAOE},
	},
	// Replay 8941817475 Slark
	// ===============================================================
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSlark,
		From:          gameClock(0, 28),
		To:            gameClock(0, 31),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly, TagOutplayed},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSlark,
		From:          gameClock(2, 11),
		To:            gameClock(2, 14),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "zames",
		Description:   "",
		ReplayHero:    rhSlark,
		From:          gameClock(3, 0),
		To:            gameClock(3, 15),
		CreepContains: bm,
		ExpectMiss:    false,
		Tags:          []CaseTag{},
	},
	{
		Label:         "zames",
		Description:   "",
		ReplayHero:    rhSlark,
		From:          gameClock(4, 20),
		To:            gameClock(4, 45),
		CreepContains: bm,
		ExpectMiss:    false,
		Tags:          []CaseTag{},
	},
	{
		Label:         "impossible lh",
		Description:   "",
		ReplayHero:    rhSlark,
		From:          gameClock(5, 42),
		To:            gameClock(5, 45),
		CreepContains: bf,
		ExpectMiss:    false,
		Tags:          []CaseTag{TagImpossible},
	},
	{
		Label:         "zames",
		Description:   "",
		ReplayHero:    rhSlark,
		From:          gameClock(5, 50),
		To:            gameClock(6, 25),
		CreepContains: bm,
		ExpectMiss:    false,
		Tags:          []CaseTag{},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSlark,
		From:          gameClock(6, 51),
		To:            gameClock(6, 53),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	{
		Label:         "missed due to dark pact",
		Description:   "",
		ReplayHero:    rhSlark,
		From:          gameClock(8, 54),
		To:            gameClock(8, 57),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagAOE, TagTooEarly},
	},
	{
		Label:         "missed due to dark pact",
		Description:   "",
		ReplayHero:    rhSlark,
		From:          gameClock(9, 54),
		To:            gameClock(9, 57),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagAOE, TagTooEarly},
	},
	{
		Label:         "missed due to dark pact",
		Description:   "",
		ReplayHero:    rhSlark,
		From:          gameClock(10, 25),
		To:            gameClock(10, 27),
		CreepContains: bm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagAOE, TagTooEarly},
	},
	// Replay 8941733752 Sven
	// =======================================
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSven,
		From:          gameClock(2, 3),
		To:            gameClock(2, 7),
		CreepContains: gm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSven,
		From:          gameClock(3, 12),
		To:            gameClock(3, 15),
		CreepContains: gm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagTower, TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSven,
		From:          gameClock(3, 32),
		To:            gameClock(3, 37),
		CreepContains: gm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSven,
		From:          gameClock(3, 37),
		To:            gameClock(3, 39),
		CreepContains: gm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSven,
		From:          gameClock(3, 42),
		To:            gameClock(3, 46),
		CreepContains: gf,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagUncontested},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSven,
		From:          gameClock(4, 18),
		To:            gameClock(4, 20),
		CreepContains: gm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooLate},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSven,
		From:          gameClock(6, 10),
		To:            gameClock(6, 11),
		CreepContains: gr,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagTooEarly},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSven,
		From:          gameClock(13, 16),
		To:            gameClock(13, 21),
		CreepContains: gm,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAOE},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSven,
		From:          gameClock(13, 51),
		To:            gameClock(13, 55),
		CreepContains: gr,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagAutoAttack, TagTooEarly},
	},
	// Replay 8951306658 Jakiro
	// =========================================================
	{
		Label:         "used dual breath and there is enemies nearby",
		Description:   "",
		ReplayHero:    rhJakiro,
		From:          gameClock(8, 59),
		To:            gameClock(9, 3),
		CreepContains: bm,
		ExpectMiss:    false,
		Tags:          []CaseTag{},
	},
	{
		Label:         "",
		Description:   "",
		ReplayHero:    rhSkywrathMage,
		From:          gameClock(36, 34),
		To:            gameClock(36, 37),
		CreepContains: gf,
		ExpectMiss:    true,
		Tags:          []CaseTag{TagSpell, TagAOE, TagTooEarly, TagFreeFarming},
	},
}
